# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build_and_test
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
      ng build --prod
    displayName: 'npm install and build'

  - script: ng lint
    displayName: Lint
    
  - script: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    displayName: Test  

  - script: npx audit-ci -l
    displayName: Package security audit

- job: SonarCloud
  dependsOn: Build_and_test
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Sonarcloud'
      organization: 'rafaelsouza0095'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'RafaelSouza0095_FinantialBlast'
      cliProjectName: 'FinantialBlast'
      cliSources: '.'

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'